### ISSUE TITLE
salvando?

### ISSUE THREAD

**Issue by nataliabueno** [atrfisch/proportional_races#2]
Oi Arthur, 
Começando na linha 4900, o que são esses objetos que estamos salvando? Não encontrei onde eles foram criados. 

load(paste0(dir_d, "original_unzipped/distrital_dep_part_1998_2014.RData"))
load(paste0(dir_d, "original_unzipped/state_dep_part_1998_2014.RData"))
load(paste0(dir_d, "original_unzipped/fed_dep_part_1998_2014.RData"))
load(paste0(dir_d, "original_unzipped/ver_part_2000_2016.RData"))

**Comment by atrfisch** [comment]
Oi Natalia,
Tdo bem, estou finalmente no sanduíche. Estou morando em Cambridge e trabalhando daqui. Queria incluir nesta base depois dados de financiamento e gastos.

Respondendo sua pergunta. Os objetos que começam na linha 4900 são o resultado da manipulações todas. Neste código eu só recarrego eles para rodar testes.

Eu salvo estes objetos da linha das linhas 4870 até 4883, o seguinte código:

# Saving datasets with partisan votes

distrital_dep_1998_2014 <- list(distrital_dep_1998, distrital_dep_2002, distrital_dep_2006, distrital_dep_2010, distrital_dep_2014)
save(distrital_dep_1998_2014, file = paste0(dir_d, "original_unzipped/distrital_dep_1998_2014.RData"))

state_dep_1998_2014 <- list(state_dep_1998, state_dep_2002, state_dep_2006, state_dep_2010, state_dep_2014)
save(state_dep_1998_2014, file = paste0(dir_d, "original_unzipped/state_dep_1998_2014.RData"))

fed_dep_1998_2014 <- list(fed_dep_1998, fed_dep_2002, fed_dep_2006, fed_dep_2010, fed_dep_2014)
save(fed_dep_1998_2014, file = paste0(dir_d, "original_unzipped/fed_dep_1998_2014.RData"))

ver_2000_2016 <- list(ver_2000, ver_2004, ver_2008, ver_2012, ver_2016)
save(ver_2000_2016, file = paste0(dir_d, "original_unzipped/ver_2000_2016.RData"))

**Comment by nataliabueno** [comment]
Parabéns! Depois te mando email sobre o sanduíche, estarei perto de você em algum momento. 

1) Seria ótimo incluir os dados de financiamento e gastos. Posso ajudar. 

2) Sobre o código. Essas linhas que você colocou não salvam os objetos que eu coloquei:

distrital_dep_1998_2014.RData != distrital_dep_part_1998_2014.RData

Vê a diferença? Ou eu que não estou entendendo? O objeto distrital_dep_1998_2014.RData (e equivalentes para outros cargos) tem o resultado final, mas o objeto distrital_dep_part_1998_2014.RData (e equivalentes para outros cargos) não está criado em outro lugar

**Comment by nataliabueno** [comment]
Obs.: estou mexendo em detalhes aqui e depois faço o push do que eu fiz e atualizo a descrição do repo.

**Comment by atrfisch** [comment]
Ah entendi o que aconteceu Natalia,

Estes objetos com o _part eram as bases que incluiam a votação do partido como se fosse uma observação e não uma coluna. Esse é um código que ficou de versões passadas e não faz mais sentido, pois integramos os votos na legenda como coluna. Desculpa por isso.

**Comment by nataliabueno** [comment]
Ah, ok! No prob. Vou arrumar lá. Abs.
